name: CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure Cache
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-cmake-build-${{ hashFiles('CMakeLists.txt') }}

    - name: Set Compiler Options  # 启用严格警告
      run: echo "CMAKE_CXX_FLAGS=\"-Wall -Wextra\"" >> build/CMakeCache.txt

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest -C $(echo ${{env.BUILD_TYPE}} | tr '[:lower:]' '[:upper:]')  # 解决大小写敏感

    - name: Upload Artifacts  # 归档产物
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          build/bin/*
          build/lib/*
